// Code generated by protoc-gen-go.
// source: msg.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	PbFrame
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PbFrame struct {
	SrcUrl           *string  `protobuf:"bytes,1,req,name=src_url,json=srcUrl" json:"src_url,omitempty"`
	DstUrls          []string `protobuf:"bytes,2,rep,name=dst_urls,json=dstUrls" json:"dst_urls,omitempty"`
	AccId            *int64   `protobuf:"varint,3,opt,name=acc_id,json=accId" json:"acc_id,omitempty"`
	MsgRaw           []byte   `protobuf:"bytes,4,opt,name=msg_raw,json=msgRaw" json:"msg_raw,omitempty"`
	Offline          *bool    `protobuf:"varint,5,opt,name=offline,def=0" json:"offline,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PbFrame) Reset()                    { *m = PbFrame{} }
func (m *PbFrame) String() string            { return proto.CompactTextString(m) }
func (*PbFrame) ProtoMessage()               {}
func (*PbFrame) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_PbFrame_Offline bool = false

func (m *PbFrame) GetSrcUrl() string {
	if m != nil && m.SrcUrl != nil {
		return *m.SrcUrl
	}
	return ""
}

func (m *PbFrame) GetDstUrls() []string {
	if m != nil {
		return m.DstUrls
	}
	return nil
}

func (m *PbFrame) GetAccId() int64 {
	if m != nil && m.AccId != nil {
		return *m.AccId
	}
	return 0
}

func (m *PbFrame) GetMsgRaw() []byte {
	if m != nil {
		return m.MsgRaw
	}
	return nil
}

func (m *PbFrame) GetOffline() bool {
	if m != nil && m.Offline != nil {
		return *m.Offline
	}
	return Default_PbFrame_Offline
}

func init() {
	proto.RegisterType((*PbFrame)(nil), "pb.PbFrame")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x34, 0xcc, 0xb1, 0xaa, 0x83, 0x30,
	0x14, 0x80, 0x61, 0xa2, 0x57, 0xa3, 0xe1, 0x4e, 0x81, 0xd2, 0x74, 0x6a, 0xe8, 0x94, 0xa9, 0x0f,
	0xd0, 0x07, 0x28, 0x74, 0x2b, 0x01, 0x67, 0x39, 0x9e, 0xa8, 0x08, 0x49, 0x95, 0x73, 0x2c, 0xbe,
	0x45, 0x9f, 0xb9, 0x38, 0x74, 0xfd, 0x7f, 0xf8, 0x54, 0x9d, 0x78, 0xbc, 0x2e, 0x34, 0xaf, 0xb3,
	0xce, 0x96, 0xee, 0xf2, 0x11, 0x4a, 0x3e, 0xbb, 0x3b, 0x41, 0xea, 0xf5, 0x51, 0x49, 0x26, 0x6c,
	0xdf, 0x14, 0x8d, 0xb0, 0x99, 0xab, 0x7d, 0xc9, 0x84, 0x0d, 0x45, 0x7d, 0x52, 0x55, 0xe0, 0x75,
	0x1f, 0x6c, 0x32, 0x9b, 0xbb, 0xda, 0xcb, 0xc0, 0x6b, 0x43, 0x91, 0xf5, 0x41, 0x95, 0x80, 0xd8,
	0x4e, 0xc1, 0xe4, 0x56, 0xb8, 0xdc, 0x17, 0x80, 0xf8, 0x08, 0x3b, 0x95, 0x78, 0x6c, 0x09, 0x36,
	0xf3, 0x67, 0x85, 0xfb, 0xf7, 0x65, 0xe2, 0xd1, 0xc3, 0xa6, 0xcf, 0x4a, 0xce, 0xc3, 0x10, 0xa7,
	0x57, 0x6f, 0x0a, 0x2b, 0x5c, 0x75, 0x2b, 0x06, 0x88, 0xdc, 0xfb, 0x5f, 0xfd, 0x06, 0x00, 0x00,
	0xff, 0xff, 0x24, 0xe1, 0xdb, 0xf7, 0xa0, 0x00, 0x00, 0x00,
}
